#!/bin/sh -e

if [ -z "$1" ] ; then echo "usage: load-key keyname" ; exit 1 ; fi

KEYSTORE=/Volumes/key/ssh
KEYFILE=$( find "${KEYSTORE}/" -name "id_*-$1" | head -1)
FILE="${HOME}/.ssh/.ssh-agent-$1"

if [ ! -f "${FILE}" ] ; then echo "no agent environment at ${FILE}" ; exit 1 ; fi
if [ ! -f "${KEYFILE}" ] ; then echo "no key at ${KEYFILE}" ; exit 1; fi

# shellcheck disable=1090
. "${FILE}"

# Add the named key to the agent, with prompting turned on
if [ -z "${USE_STDIN}" ] ; then
  ssh-add -c "${KEYFILE}"
else
  SSH_ASKPASS=ssh-agent-loader SSH_ASKPASS_REQUIRE=force setsid -w ssh-add -c "${KEYFILE}"
fi
