#!/usr/bin/env bash

AGENT=${1:-}
MINUTES=${2:-10}

unyolo() {
  notify "unyolo ${AGENT}" || true
  ssh-undefeat "${AGENT}" || true
}
trap unyolo ERR EXIT

notify() {
  terminal-notifier -title SSH -subtitle "¯\_(ツ)_/¯" -group ssh-askpass -message "$@" -sound Tink >/dev/null 2>&1
}

if [ -z "${AGENT}" ] ; then
  notify "no agent to yolo"
  exit 1
fi

SECONDS=$(( MINUTES * 60 ))
notify "yolo ${AGENT} (${SECONDS})"
ssh-agent-auth
ssh-defeat "$1"
sleep ${SECONDS}
# ssh-undefeat via exit handler
